### ISSUE TITLE
Enable Plack and memcached by default

### ISSUE THREAD

**Issue by joubu** [digibib/kohadevbox#116]
Plack and Memcached should be enabled by default

**Comment by tomascohen** [comment]
Done!

**Comment by joubu** [comment]
koha-plack --enable returns an error code (1) if plack is already enabled and so the `vagrant up` command fails:

TASK [kohadevbox : Enable Plack] ***********************************************
fatal: [jessie]: FAILED! => {"changed": true, "cmd": ["koha-plack", "--enable", "kohadev"], "delta": "0:00:00.118633", "end": "2016-10-27 11:23:20.287461", "failed": true, "rc": 1, "start": "2016-10-27 11:23:20.168828", "stderr": "Plack already enabled for kohadev", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by joubu** [comment]
I have tried with
  command: koha-plack --enable {{ koha_instance_name }} > /dev/null 2>&1 || /bin/true
And I still get the same error, odd...
There is certainly a trick to tell vagrant to continue even if the command failed.

**Comment by joubu** [comment]
https://docs.ansible.com/ansible/playbooks_error_handling.html
says to use ignore_errors: yes
